//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolJournalApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public /*partial*/ class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.Students = new HashSet<Students>();
            this.Teachers = new HashSet<Teachers>();
        }

        public Persons(string connName, string Name, string Email, string Phone, string Address)
        {
            this.PersonID = PersonManager.AddPerson(connName, Name, Email, Phone, Address);
        }
    
        public int PersonID { get; set; }

        [Required]
        [DisplayName("Name ")]
        public string PersonName { get; set; }

        [Required]
        [EmailAddress]
        [DisplayName("E-mail ")]
        public string PersonEmail { get; set; }

        [Required]
        [Phone]
        [DisplayName("Phone ")]
        public string PersonPhone { get; set; }

        [Required]
        [DisplayName("Address ")]
        public string PersonAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
